django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from movie import views

app_name = 'base'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index, name='base'),
    url(r'^movie/', include('movie.urls'))
]

# /static/에 대한 요청을 STATIC_ROOT 경로의 파일에서 찾는다
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# /media/에 대한 요청을 MEDIA_ROOT 경로의 파일에서 찾는다
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/movie/urls.py
from django.conf.urls import url

from movie import views

app_name = 'movie'

urlpatterns = [
    url(r'^statistics/', views.statistics),
    url(r'^search/', views.search, name='api_search'),
    url(r'^select/', views.select, name='select'),
    url(r'^app_test/', views.app_test)
]

django_app/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):

    USER_TYPE_DJANGO = 'D'
    USER_TYPE_FACEBOOK = 'F'
    USER_TYPE_NAVER = 'N'
    USER_TYPE_CHOICES = (
        (USER_TYPE_DJANGO, 'Django'),
        (USER_TYPE_FACEBOOK, 'Facebook'),
        (USER_TYPE_NAVER, 'Naver'),
    )

    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES, default="D")
    email = models.EmailField(max_length=255, unique=True)
    nickname = models.CharField(max_length=20, unique=True, null=True)

    def __str__(self):
        return self.nickname or self.email

django_app/movie/models.py
import json

from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from config import settings

User = get_user_model()

class Movie(models.Model):
    title = models.CharField(max_length=30)
    sub_title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    director = models.CharField(max_length=50)
    actor = models.CharField(max_length=50)
    content = models.TextField()
    link = models.TextField(max_length=255)
    userRating = models.IntegerField()
    poster_image = models.ImageField(upload_to='movie', blank=False)

    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    rating_by_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Comment',
        related_name='user_rating'
    )


class SelectedMovie(models.Model):
    movie = models.ForeignKey(Movie)
    selector = models.CharField(max_length=10)
    selected_date = models.CharField(max_length=15)
    reviewer = models.ManyToManyField(User)


class Comment(models.Model):
    movie = models.ForeignKey(Movie)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    ratings = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

django_app/member/views.py
from django.shortcuts import render

# Create your views here.

django_app/movie/views.py
import datetime
import json
import urllib.request

from pprint import pprint

from django.http import HttpResponse
from django.shortcuts import render
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

# Create your views here.
from config.settings import CONFIG_SECRET_DEBUG_FILE
from movie.models import Movie, SelectedMovie


def index(request):
    return render(request, 'base/base.html')

def statistics(request):

    from matplotlib.figure import Figure

    fig = Figure()
    now = datetime.datetime.now()
    delta = datetime.timedelta(days=1)

    value = np.random.standard_normal(40)
    index = range(len(value))

    # 여기서 그림1이 출력됨
    plt.plot(index, value)  # 선이나 마커를 플롯하는 함수

    plt.xlim(0, 20)  # x축 범위 설정
    plt.ylim(np.min(value) - 1,
             np.min(value) + 1)  # y축 범위 설정 value 변수의 최솟값보다 하나 작은 값으로 아래 한계를 정하고, 최대값보다 하나 큰 값으로 위의 한계를 정함

    # Plot 옵션 설정 및 꾸미기
    plt.figure(figsize=(7, 4))  # plot의 모양. 가로 세로가 7인치, 4인치 비로 설정
    plt.plot(value.cumsum(), 'b', lw=1.5)  # plot 함수 호출 numpy.cumsum() : plot의 새로운 figure을 생성하는 함수. 'b' : 파란색, w=1.5(표시할 스타일)
    plt.plot(value.cumsum(), 'ro')  # plot 함수 호출 'ro'는 빨간색 동그라미를 의미
    plt.xlabel('index')  # x축 이름 설정
    plt.ylabel('value')  # y축 이름 설정
    plt.title("Line Plot1")  # 플롯의 제목을 설정하는 함수
    plt.savefig("../.media/graphic/graphic.png", format='png')

    fig.autofmt_xdate()
    canvas = FigureCanvas(fig)
    response = HttpResponse(content_type='image/png')
    canvas.print_png(response)
    mpl.pyplot.close(fig)

    return render(request, 'statistics/statistics.html')

def search(request):

    if request.method == 'GET':
        config_secret_debug = json.loads(open(CONFIG_SECRET_DEBUG_FILE).read())
        client_id = config_secret_debug['NAVER']['CLIENT_ID']
        client_secret = config_secret_debug['NAVER']['CLIENT_SECRET']
        q = request.GET.get('q')
        encText = urllib.parse.quote("{}".format(q))
        url = "https://openapi.naver.com/v1/search/movie?query=" + encText  # json 결과
        movie_api_request = urllib.request.Request(url)
        movie_api_request.add_header("X-Naver-Client-Id", client_id)
        movie_api_request.add_header("X-Naver-Client-Secret", client_secret)
        response = urllib.request.urlopen(movie_api_request)
        rescode = response.getcode()
        if (rescode == 200):
            response_body = response.read()
            result = json.loads(response_body.decode('utf-8'))
            items = result.get('items')
            pprint(result)

            context = {
                'items': items
            }
            return render(request, 'search/search.html', context=context)

def select(request):
    print(request.GET)
    if request.method == 'GET':
        title = request.GET.get('movieTitle')
        director = request.GET.get('movieActor')
        rating = request.GET.get('movieRating')
        link = request.GET.get('movieImageLink')
        dating = request.GET.get('idTourDateDetails')
        # SelectedMovie.objects.save()
        SelectedMovie.objects.create(title=title, director=director, userRating=rating, link=link, dating=dating)
    return render(request, 'search/search.html')


def app_test(request):
    return render(request, 'app_test/test.html')

django_app/views.py
from django.shortcuts import render


def index(request):
    pass

django_app/templates/app_test/test.html
{% extends 'base/base.html' %}
{% block content %}
<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Launch demo modal</button>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title" id="myModalLabel">Modal title</h4>

            </div>
            <div class="modal-body">
                <div class="col-md-12">
                    <div class="row">
                        <label for="idTourDateDetails">Tour Start Date:</label>
                        <div class="form-group">
                            <div class="input-group">
                            <input type="date" name="idTourDateDetails" id="idTourDateDetails" class="form-control clsDatePicker"> <span class="input-group-addon"><i id="calIconTourDateDetails" class="glyphicon glyphicon-th"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<script>
    $('#idTourDateDetails').datepicker();


</script>

{% endblock %}

django_app/templates/search/search.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <h1> 네이버 영화 검색 API</h1>

  <form action="{% url 'movie:api_search' %}" method="GET" >
      <input class="form-control" name="q" placeholder="검색할 단어를 입력">
      <input class="btn btn-primary" type="submit" value="검색">
  </form>

  <!-- Trigger the modal with a button -->
  <!--<button type="button" class="btn btn-info btn-lg modal-lg" data-toggle="modal" data-target="#myModal">이번주 영화로 선정하기</button>-->
  <!-- Modal -->

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" >
      <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <form action="{% url 'movie:select' %}" method="GET">
          <div class="modal-content">
            <div class="modal-header">
             <div class="form-group">
              <div class="input-group">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <!--<h4 class="modal-title"><p><input type="text" class="input-sm" id="movieTitle"/></p></h4>-->
                <h3><input type="text" name="movieTitle" id="movieTitle" class="input-sm"></h3>
                <!--<h4<input type="text" class="input-sm" id="movieTitle"/>-->
              </div>
             </div>
            </div>
            <!-- Modal Body -->
            <div class="modal-body">
              <img id="movieImage" src="{{ item.image }}" width="400" height="400">
              <button>사진 변경</button>
              <input type="text" name="movieDirector" id="movieDirector" class="input-sm" style="display:none;">
              <input type="text" name="movieActor" id="movieActor" class="input-sm" style="display:none;">
              <input type="text" name="movieRating" id="movieRating" style="display:none;">
              <input type="text" name="movieImageLink" id="movieImageLink" style="display:none;">

              <!-- 캘린더 -->
              <div id="datetimepicker1" class="input-append date">
                <label for="idTourDateDetails">선정일</label>
                  <div class="form-group">
                      <div class="input-group">
                        <input type="date" name="idTourDateDetails" id="idTourDateDetails" class="form-control clsDatePicker"> <span class="input-group-addon"><i id="calIconTourDateDetails" class="glyphicon glyphicon-th"></i></span>
                      </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                  <button type="submit" class="btn btn-default btn-success btn-block" >Submit</button>
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  <!-- Modal End -->

  <table class="table table-condensed table-hover table-bordered" id="movie_api">
    <thead class="thead-inverse">
      <tr>
        <th>번호</th>
        <th>포스터</th>
        <th>제목(출시연도)</th>
        <th>감독</th>
        <th>배우</th>
        <th>평점</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
        <tr id="tr_{{ forloop.counter }}">
          <td>{{ forloop.counter }}</td>
          <td>
          {% if item.image %}
            <!--이미지가 있으면 네이버가 제공하는 포스터 사용-->
            <img src="{{item.image}}"  width="110" height="150" data-toggle="modal" data-img-url="{{item.image}}" >
          {% else %}
            <!--이미지가 없으면 디폴트 이미지를 출력-->
            <img src="{% static 'images/no-image.png' %}" alt="" width="110" height="150">
          {% endif %}
          </td>
          <td> {{ item.title|safe }} ({{ item.pubDate }})</td>
          <td> {{ item.director }}</td>
          <td> {{ item.actor }}</td>
          <td> {{ item.userRating }}</td>
          <td style="display:none;"> {{ item.image }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>


{% endblock %}

django_app/templates/statistics/statistics.html
{% load static %}
<h1>통계 결과</h1>

<img src="/.media/graphic/graphic.png" alt="">